---
title: "Untitled"
author: "Vadim Karnaukhov"
date: "13 01 2021"
output: html_document
---

```{r Changed}
potentials <- #fread("~/struct2020/TCRen_MJ.csv") %>% 
  #merge(fread("~/struct2020/contacts_a_s.csv") %>% 
  #        select(type, residue.aa.from, residue.aa.to, odds) %>% 
  #        dcast(residue.aa.from + residue.aa.to ~ type)) %>% 
  #select(-odds, -E1, -E2, -E12) %>% 
  compute_TCRen(pdb_nonred_list(0, "old"), "all") %>% 
  merge(compute_TCRen(pdb_nonred_list(.7, "old"), "70"))

cor(potentials[,-c(1,2)])

potentials <- pot.pseudocount.noC

potentials <- compute_TCRen(pdb.nonred, "70") %>% 
  merge(pot.count)

potentials <- tcren.mean.flat
```




Function for creation of a dataframe with contacts between CDR3 and peptide starting from MIR output
```{r}
#dir_name <- "benchmark/TCR55/6bj8/out_mir/"

df_contacts <- function(dir_name) {
  contacts <- fread(paste0(dir_name, "atomdist.txt")) %>%
    filter(dist <= 5, chain.id.from != chain.id.to) %>%
    select(-atom.from, -atom.to, -dist) %>%
    unique
  
  contacts.1 <- contacts
  contacts.1$chain.id.from <- contacts$chain.id.to
  contacts.1$chain.id.to <- contacts$chain.id.from
  contacts.1$residue.index.from <- contacts$residue.index.to
  contacts.1$residue.index.to <- contacts$residue.index.from
  
  contacts <- contacts %>%
    rbind(contacts.1)
  
  resmarkup <- fread(paste0(dir_name, "resmarkup.txt"), blank.lines.skip = T)
  
  general <- fread(paste0(dir_name, "general.txt"))
  
  resmarkup.a <- resmarkup %>%
    merge(general)
  
  #merge = data.table::merge.data.table
  
  contacts.a <- contacts %>%
    merge(resmarkup.a %>% mutate(chain.id.from = chain.id,
                                 chain.type.from = chain.type,
                                 chain.supertype.from = chain.supertype,
                                 region.type.from = region.type,
                                 residue.index.from = residue.index,
                                 residue.aa.from = residue.aa) %>%
            select(pdb.id, chain.id.from, chain.type.from, chain.supertype.from,
                   complex.species,
                   region.type.from, residue.index.from, residue.aa.from)) %>%
    merge(resmarkup.a %>% mutate(chain.id.to = chain.id,
                                 chain.type.to = chain.type,
                                 chain.supertype.to = chain.supertype,
                                 region.type.to = region.type,
                                 residue.index.to = residue.index,
                                 residue.aa.to = residue.aa) %>%
            select(pdb.id, chain.id.to, chain.type.to, chain.supertype.to,
                   region.type.to, residue.index.to, residue.aa.to),
          by = c("pdb.id", "chain.id.to", "residue.index.to"))
  
  resides.from <- resmarkup %>%
    merge(general) %>%
    #filter(startsWith(region.type, "CDR3")) %>%
    filter(startsWith(region.type, "CDR")) %>%
    mutate(chain.type.from = chain.type,
           region.type.from = region.type,
           residue.index.from = residue.index,
           residue.aa.from = residue.aa) %>%
    group_by(pdb.id, chain.type.from, region.type.from) %>%
    mutate(pos.from = residue.index.from - min(residue.index.from),
           len.from = max(pos.from) + 1) %>%
    select(pdb.id, chain.type.from, region.type.from, residue.index.from, 
           pos.from, len.from, residue.aa.from) %>%
    ungroup %>%
    arrange(pdb.id, chain.type.from, residue.index.from)
  
  resides.to <- resmarkup %>%
    merge(general) %>%
    filter(region.type == "PEPTIDE") %>%
    mutate(chain.type.to = chain.type,
           region.type.to = region.type,
           residue.index.to = residue.index,
           residue.aa.to = residue.aa) %>%
    group_by(pdb.id, chain.type.to, region.type.to) %>%
    mutate(pos.to = residue.index.to - min(residue.index.to),
           len.to = max(pos.to) + 1) %>%
    select(pdb.id, chain.type.to, region.type.to, residue.index.to, 
           pos.to, len.to, residue.aa.to) %>%
    ungroup %>%
    arrange(pdb.id, chain.type.to, residue.index.to)
  
  resides.comb <- resides.from %>%
    merge.data.frame(resides.to)
  
  contacts.real <- resides.comb %>%
    merge(contacts.a %>%
            #filter(region.type.from == "CDR3", chain.type.to == "PEPTIDE") %>%
            mutate(contact = 1) %>%
            select(pdb.id, chain.type.from, residue.index.from, residue.index.to, contact),
          all.x = T) %>%
    mutate(contact = ifelse(is.na(contact), 0, contact)) %>% 
    merge.data.frame(general %>% 
            filter(chain.component == "PEPTIDE") %>% 
            select(pdb.id, peptide = allele.info))
  
  return(contacts.real)
  #contacts.real %>% 
  #  filter(contact == 1) %>% 
  #  group_by(pdb.id) %>% 
  #  summarise(n = n()) %>% 
  #  arrange(-n) %>% 
  #  ggplot(aes(x = n)) +
  #  geom_histogram(binwidth = 1)
}
```

## Function for summarising TCRen and MJ

```{r Changed}
summarise_TCRen_MJ <- function(df) {
  df %>%   
    summarize(#mj.s = sum(mj * contact),
              #mj2.s = sum(mj2 * contact),            
              #all.s = -sum(all * contact),
              #contacts.s = sum(contact),
              cdrps.s = -sum(cdrps.all * contact),
              cdrpa.s = -sum(cdrpa.all * contact),
              cdrpa.nonsym.s = -sum(cdrpa.nonsym.all * contact),
              cdrps.70.s = -sum(cdrps.70 * contact),
              cdrpa.70.s = -sum(cdrpa.70 * contact),
              cdrpa.nonsym.70.s = -sum(cdrpa.nonsym.70 * contact)
              )
}

summarise_TCRen_MJ <- function(df) {
  df %>%   
    summarize(cdrps.plus1.s = -sum(cdrps.plus1 * contact),
              cdrps.plus0.1.s = -sum(cdrps.plus0.1 * contact),
              cdrps.plus1.noC.s = -sum(cdrps.plus1.noC * contact),
              cdrps.plus0.1.noC.s = -sum(cdrps.plus0.1.noC * contact)
              )
}

summarise_TCRen_MJ <- function(df) {
  df %>%   
    summarize(cdrps.70.s = -sum(cdrps.70 * contact),
              cdrpa.70.s = -sum(cdrpa.70 * contact),
              cdrpa.nonsym.70.s = -sum(cdrpa.nonsym.70 * contact),
              cdrps.count.s = -sum(cdrps.count * contact),
              cdrpa.count.s = -sum(cdrpa.count * contact),
              cdrpa.nonsym.count.s = -sum(cdrpa.nonsym.count * contact)
              )
}

summarise_TCRen_MJ <- function(df) {
  df %>%   
    summarize(cdrpa.nonsym.70.s = -sum(cdrpa.nonsym.70 * contact),
              cdrpa.70.s = -sum(cdrpa.70 * contact),
              cdrps.70.s = -sum(cdrps.70 * contact),              
              cdrpa.nonsym.normflat.s = -sum(cdrpa.nonsym.normflat * contact),
              cdrpa.nonsym.normmean.s = -sum(cdrpa.nonsym.normmean * contact),
              cdrpa.normflat.s = -sum(cdrpa.normflat * contact),
              cdrpa.normmean.s = -sum(cdrpa.normmean * contact),
              cdrps.normflat.s = -sum(cdrps.normflat * contact),
              cdrps.normmean.s = -sum(cdrps.normmean * contact),
              mj.s = -sum(mj * contact),
              mj2.s = -sum(mj2 * contact),
              mi.cdrpa.nonsym.70.s = -sum(mi.cdrpa.nonsym.70 * contact),
              mi.cdrps.70.s = -sum(mi.cdrps.70 * contact)
              )
}

potentials %>% colnames()
```

```{r}
#summarise_TCRen_MJ <- function(df) {
#  df %>%   
#    filter(contact == 1) %>% 
#    summarize(mj.s = mean(mj * contact),
#              mj2.s = mean(mj2 * contact),            
#              all.s = -mean(all * contact),
#              cdrps.s = -mean(cdrps * contact),
#              cdrpa.s = -mean(cdrpa * contact),
#              cdrpa.nonsym.s = -mean(cdrpa.nonsym * contact))
#
```


##TCR55 test case (https://www.sciencedirect.com/science/article/pii/S0092867418307852#bib6)


```{r}
tcr55.peptides <- fread("benchmark/TCR55/display_TCR55.csv") %>% 
  mutate(group = "recognised") %>% 
  rbind(fread("benchmark/TCR55/iedb_B3501.csv") %>% 
          mutate(group = "iedb_B3501")) %>% 
  distinct()
```


### Functions for ROC AUC
```{r}
library(plotROC)
library(pROC)

plot_roc_curve <- function(df) {
  df %>% 
    ggplot(aes(d = group, m = -value, color = potential)) +
    geom_vline(xintercept = 1, size = 1) +
    geom_abline(intercept = 1, slope = 0, size = 1) +
    geom_roc(n.cuts = 0, size = .5) + 
    style_roc(major.breaks = c(0, 0.25, 0.5, 0.75, 1), minor.breaks = F, theme = theme_classic) + 
    geom_abline(intercept = 0, slope = 1, linetype="dashed") +
    labs(color = "Potential", x = 'False positive rate', y = 'True positive rate') +
    scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))
}

plot_potentials <- function(df) {
  df %>% 
    ggplot(aes(x = group, y = value)) +
    facet_wrap(~potential, scales = "free_y", nrow = 2) +
    geom_quasirandom(size = .5) +
    geom_boxplot(alpha = 0, color = 'red') +
    theme_minimal()
}

calc_roc_auc <- function(df1) {
  print("")
  for (pot in df1$potential %>% unique()) {
    df <- df1 %>% 
        filter(potential == pot) #%>% 
        #mutate(group = (group == "recognised"))
    roc_auc <- auc(roc(df$group, df$value, direction = ">", levels = c(F,T)))
    cat(paste(round(roc_auc, 2), "\t", pot, "\n"))
  }  
}
```



Function for calculation of energy of interaction (TCRen, MJ and others) starting from df_contacts df

```{r}
#tcr55.contacts <- df_contacts("benchmark/TCR55/6bj3/out_mir/")

tcr55.energy <- tcr55.contacts %>% 
  merge.data.frame(tcr55.peptides) %>% 
  merge.data.frame(potentials) %>% 
  group_by(pdb.id, group) %>% 
  summarise_TCRen_MJ()  

tcr55.energy.a <- tcr55.energy %>% 
  melt(id = c("pdb.id", "group"), variable.name = "potential") 

tcr55.energy.a %>% 
  mutate(group = (group == "recognised")) %>% 
  plot_roc_curve()

tcr55.energy.a %>% 
  plot_potentials()

tcr55.energy.a %>% 
  mutate(group = (group == "recognised")) %>%
  calc_roc_auc()
```


##DMF5 test case (Gee et al., 2018)

```{r}
dmf5.peptides <- fread("benchmark/DMF5/display_GIG.csv") %>% 
  mutate(group = "GIG") %>% 
  rbind(fread("benchmark/DMF5/display_DRG.csv") %>% 
          mutate(group = "DRG")) %>% 
  rbind(fread("benchmark/DMF5/iedb_A0201.csv") %>% 
          mutate(group = "iedb_A0201")) %>%
  rbind(fread("benchmark/DMF5/display_GIG_conf.csv") %>% 
          mutate(group = "GIG")) %>% 
  rbind(fread("benchmark/DMF5/display_DRG_conf.csv") %>% 
          mutate(group = "DRG")) %>% 
  merge(fread("benchmark/DMF5/display_GIG_conf.csv") %>% 
          mutate(confirmed = 1) %>% 
          rbind(fread("benchmark/DMF5/display_DRG_conf.csv") %>% 
                  mutate(confirmed = 1)), 
        all = T) %>% 
  mutate(confirmed = replace_na(confirmed, 0)) %>% 
  distinct()
```

```{r}
#dmf5_GIG.contacts <- df_contacts("benchmark/DMF5/3qdg/out_mir/")

dmf5_GIG.energy <- dmf5_GIG.contacts %>% 
  merge.data.frame(dmf5.peptides) %>% 
  merge.data.frame(potentials) %>% 
  group_by(pdb.id, group, confirmed) %>% 
  summarise_TCRen_MJ()  

dmf5_GIG.energy.a <- dmf5_GIG.energy %>% 
  melt(id = c("pdb.id", "group", "confirmed"), variable.name = "potential") 

dmf5_GIG.energy.a %>% 
  mutate(group = (group == "GIG")) %>% 
  plot_roc_curve()

dmf5_GIG.energy.a %>% 
  mutate(group = (group == "GIG")) %>%
  calc_roc_auc()

dmf5_GIG.energy.a %>% 
  ggplot(aes(x = group, y = value, color = factor(confirmed))) +
  facet_wrap(~potential, scales = "free_y", nrow = 2) +
  geom_quasirandom(size = .3) +
  geom_boxplot(alpha = .3) +
  scale_color_manual(values = c("black", "red")) +
  theme_minimal() +
  theme(legend.position = "None")


dmf5_GIG.energy.a %>% 
  mutate(group = (group == "DRG")) %>% 
  plot_roc_curve()

dmf5_GIG.energy.a %>% 
  mutate(group = (group == "DRG")) %>%
  calc_roc_auc()
```

```{r}
#dmf5_DRG.contacts <- df_contacts("benchmark/DMF5/6amu/out_mir/")

dmf5_DRG.energy <- dmf5_DRG.contacts %>% 
  merge.data.frame(dmf5.peptides) %>% 
  merge.data.frame(potentials) %>% 
  group_by(pdb.id, group, confirmed) %>% 
  summarise_TCRen_MJ()  

dmf5_DRG.energy.a <- dmf5_DRG.energy %>% 
  melt(id = c("pdb.id", "group", "confirmed"), variable.name = "potential") 

dmf5_DRG.energy.a %>% 
  mutate(group = (group == "GIG")) %>% 
  plot_roc_curve()

dmf5_DRG.energy.a %>% 
  mutate(group = (group == "GIG")) %>%
  calc_roc_auc()

dmf5_DRG.energy.a %>% 
  ggplot(aes(x = group, y = value, color = factor(confirmed))) +
  facet_wrap(~potential, scales = "free_y", nrow = 2) +
  geom_quasirandom(size = .3) +
  geom_boxplot(alpha = .3) +
  scale_color_manual(values = c("black", "red")) +
  theme_minimal() +
  theme(legend.position = "None")


dmf5_DRG.energy.a %>% 
  mutate(group = (group == "DRG")) %>% 
  plot_roc_curve()

dmf5_DRG.energy.a %>% 
  mutate(group = (group == "DRG")) %>%
  calc_roc_auc()

```

```{r}
library(ggpubr)

dmf5_GIG_DRG <- dmf5_GIG.energy.a %>% 
  rename(peptide = pdb.id, GIG = value) %>% 
  mutate(peptide = str_split_fixed(peptide, "[_.]", 4)[,3]) %>% 
  merge(dmf5_DRG.energy.a %>% 
          rename(peptide = pdb.id, DRG = value) %>%
          mutate(peptide = str_split_fixed(peptide, "[_.]", 4)[,3])) %>% 
  melt(id = c("peptide", "group", "confirmed", "potential"), variable.name = "template") 

stat.test <- dmf5_GIG_DRG %>%
    group_by(potential, group) %>%
    wilcox_test(value ~ template, paired = T) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance()
stat.test <- stat.test %>% #add_y_position()
  add_xy_position(x = "group", dodge = 0.8)

dmf5_GIG_DRG %>% 
  ggplot(aes(x = group, y = value, color = template)) +
  facet_wrap(~potential, scales = "free") +
  geom_boxplot() +
  geom_quasirandom(dodge.width = .75, size = .1) +
  #stat_pvalue_manual(stat.test, label = "p.adj.signif", tip.length = 0.01) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  theme_bw()
dmf5_GIG_DRG %>% 
  ggplot(aes(x = group, y = value, color = template)) +
  facet_wrap(~potential, scales = "free") +
  geom_boxplot() +
  geom_quasirandom(dodge.width = .75, size = .1) +
  stat_pvalue_manual(stat.test, label = "p.adj.signif", tip.length = 0.01) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  theme_bw()

stat.test <- dmf5_GIG_DRG %>%
    group_by(potential, template) %>%
    wilcox_test(value ~ group) %>%
    adjust_pvalue(method = "BH") %>%
    add_significance()
stat.test <- stat.test %>% #add_y_position()
  add_xy_position(x = "template", dodge = 0.5)

dmf5_GIG_DRG %>% 
  ggplot(aes(x = template, y = value, color = group)) +
  facet_wrap(~potential, scales = "free_y") +
  geom_boxplot() +
  geom_quasirandom(dodge.width = .75, size = .1) +
  #stat_pvalue_manual(stat.test, label = "p.adj.signif", tip.length = 0.01) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  theme_bw()
dmf5_GIG_DRG %>% 
  ggplot(aes(x = template, y = value, color = group)) +
  facet_wrap(~potential, scales = "free_y") +
  geom_boxplot() +
  geom_quasirandom(dodge.width = .75, size = .1) +
  stat_pvalue_manual(stat.test, label = "p.adj.signif", tip.length = 0.01) +
  scale_y_continuous(expand = expansion(mult = c(0.05, 0.1))) +
  theme_bw()


```



## Shuffled complexes with matched CDR3a, CDR3b and peptide lengths

```{r}
contacts.all.e.v <- contacts.all.v %>%
  merge.data.frame(potentials)

contacts.all.e.s1.v <- contacts.all.e.v %>%
  group_by(real, pdb.id.from, pdb.id.to, chain.type.from, perspective) %>% # group by id, chain
  summarise_TCRen_MJ()
```

```{r}
contacts.all.e.s1.a.v <- contacts.all.e.s1.v %>%
  melt(id = c("pdb.id.from", "pdb.id.to", "chain.type.from", "perspective", "real"), variable.name = "potential") 

contacts.all.e.s1.a.v %>% 
  ggplot(aes(d = real, m = -value, color = potential)) +
  facet_grid(chain.type.from ~ perspective) +
  geom_vline(xintercept = 1, size = 1) +
  geom_abline(intercept = 1, slope = 0, size = 1) +
  geom_roc(n.cuts = 0, size = .5) + 
  style_roc(major.breaks = c(0, 0.25, 0.5, 0.75, 1), minor.breaks = F, theme = theme_classic) + 
  geom_abline(intercept = 0, slope = 1, linetype="dashed") +
  labs(color = "Potential", x = 'False positive rate', y = 'True positive rate') +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))

cat(paste("TRA cdr perspective\n"))
for (pot in contacts.all.e.s1.a.v$potential %>% unique()) {
  df <- contacts.all.e.s1.a.v %>% 
      filter(chain.type.from == "TRA",
             perspective == "cdr",
             potential == pot)
  roc_auc <- auc(roc(df$real, df$value, direction = ">", levels = c(F,T)))
  cat(paste(round(roc_auc, 2), "\t", pot, "\n"))
}

cat(paste("\nTRB cdr perspective\n"))
for (pot in contacts.all.e.s1.a.v$potential %>% unique()) {
  df <- contacts.all.e.s1.a.v %>% 
      filter(chain.type.from == "TRB",
             perspective == "cdr",
             potential == pot)
  roc_auc <- auc(roc(df$real, df$value, direction = ">", levels = c(F,T)))
  cat(paste(round(roc_auc, 2), "\t", pot, "\n"))
}
```

```{r}
contacts.all.e.s2.v <- contacts.all.e.v %>%
  group_by(real, pdb.id.from, pdb.id.to, perspective) %>% # group by id, chain
  summarise_TCRen_MJ()

contacts.all.e.s2.a.v <- contacts.all.e.s2.v %>%
  melt(id = c("pdb.id.from", "pdb.id.to", "perspective", "real"), variable.name = "potential") 

contacts.all.e.s2.a.v %>% 
  ggplot(aes(d = real, m = -value, color = potential)) +
  facet_grid( ~ perspective) +
  geom_vline(xintercept = 1, size = 1) +
  geom_abline(intercept = 1, slope = 0, size = 1) +
  geom_roc(n.cuts = 0, size = .5) + 
  style_roc(major.breaks = c(0, 0.25, 0.5, 0.75, 1), minor.breaks = F, theme = theme_classic) + 
  geom_abline(intercept = 0, slope = 1, linetype="dashed") +
  labs(color = "Potential", x = 'False positive rate', y = 'True positive rate') +
  scale_x_continuous(expand = c(0, 0)) + scale_y_continuous(expand = c(0, 0))

cat(paste("cdr perspective\n"))
for (pot in contacts.all.e.s2.a.v$potential %>% unique()) {
  df <- contacts.all.e.s2.a.v %>% 
      filter(perspective == "cdr",
             potential == pot)
  roc_auc <- auc(roc(df$real, df$value, direction = ">", levels = c(F,T)))
  cat(paste(round(roc_auc, 2), "\t", pot, "\n"))
}

cat(paste("\npeptide perspective\n"))
for (pot in contacts.all.e.s2.a.v$potential %>% unique()) {
  df <- contacts.all.e.s2.a.v %>% 
      filter(perspective == "pep",
             potential == pot)
  roc_auc <- auc(roc(df$real, df$value, direction = ">", levels = c(F,T)))
  cat(paste(round(roc_auc, 2), "\t", pot, "\n"))
}
```


```{r}
#mult_pdb_rand.contacts <- df_contacts("benchmark/mult_pdb_random/out_mir/")

mult_pdb_rand.energy <- mult_pdb_rand.contacts %>% 
  mutate(group = ifelse(substr(pdb.id, nchar(pdb.id)-5, nchar(pdb.id)) == "_c.pdb", T, F)) %>% 
  merge.data.frame(potentials) %>% 
  group_by(pdb.id, group) %>% 
  summarise_TCRen_MJ()  

mult_pdb_rand.energy.a <- mult_pdb_rand.energy %>% 
  melt(id = c("pdb.id", "group"), variable.name = "potential") 

mult_pdb_rand.pdb <- mult_pdb_rand.energy.a %>% 
  select(pdb.id) %>% 
  distinct() %>% 
  mutate(pdb = substr(pdb.id, 1, 4)) %>% 
  group_by(pdb) %>% 
  summarise(n = n()) %>% 
  filter(n > 10) %>% 
  .$pdb

mult_pdb_rand.energy.a <- mult_pdb_rand.energy.a %>% 
  filter(substr(pdb.id, 1, 4) %in% mult_pdb_rand.pdb)

mult_pdb_rand.energy.a %>% 
  plot_roc_curve()

mult_pdb_rand.energy.a %>% 
  plot_potentials()

mult_pdb_rand.energy.a %>% 
  calc_roc_auc()

mult_pdb_rand.energy.rank <- mult_pdb_rand.energy.a %>% 
  mutate(pdb = substr(pdb.id, 1, 4)) %>% 
  group_by(pdb, potential) %>% 
  mutate(value.rank = rank(value) / n()) %>% 
  filter(group == T) 

mult_pdb_rand.energy.rank %>% 
  ggplot(aes(x = potential, y = value.rank)) +
  geom_quasirandom() +
  geom_boxplot(color = 'red', alpha = 0) +
  scale_x_discrete(guide = guide_axis(angle = 30)) +
  theme_bw()

mult_pdb_rand.energy.rank %>% 
  ggplot(aes(x = value.rank, color = potential)) +
  stat_ecdf() +
  geom_abline(intercept = 0, slope = 1, linetype="dashed") +
  theme_bw()

```

