---
title: "Untitled"
author: "Vadim Karnaukhov"
date: "02 04 2022"
output: html_document
---

```{r}
bench.all_methods <- rbind(
  fread("benchmark_TCRen.csv"),
  fread("benchmark_ImRex.csv"),
  fread("benchmark_ERGO.csv"),
  fread("benchmark_TCRex.csv")
  # other methods will be added
) 

bench.all_methods

# Count number of unique CDR3B (for consistency, as some methods use only CDR3B info) entries for each epitope (exact match) in vdjdb-2021-02-02.zip
vdjdb.n <- fread("~/vdjdb/vdjdb.slim.txt") %>% 
  filter(gene == "TRB") %>% 
  select(peptide = antigen.epitope, cdr3) %>% 
  distinct() %>% 
  group_by(peptide) %>% 
  summarise(n.vdjdb = n()) %>% 
  arrange(-n.vdjdb)

vdjdb.n
```

```{r}
# all but TCRex
bench.all_methods %>% 
  merge(vdjdb.n, all.x = T) %>% 
  filter(method != "TCRex") %>% 
  mutate(n.vdjdb = replace_na(n.vdjdb, 0),
         rank = as.numeric(rank)) %>% 
  ggplot(aes(x = n.vdjdb, y = rank)) +
  geom_point() +
  geom_smooth(method = "lm", scales = "free") +
  facet_wrap(~method) +
  theme_pubclean() +
  ylab("Cognate epitope rank") +
  xlab("Number of VDJdb entries for the epitope") +
  scale_x_log10()
```


```{r}
#TCRex
bench.all_methods %>% 
  merge(vdjdb.n, all.x = T) %>% 
  filter(method == "TCRex",
         not_supported == F) %>% 
  mutate(n.vdjdb = replace_na(n.vdjdb, 0),
         rank = factor(rank, levels = c("1", "2", "Out of top", "No pred"))) %>% 
  ggplot(aes(x = rank, y = n.vdjdb)) +
  geom_boxplot() +
  geom_beeswarm() +
  theme_pubclean() +
  ylab("Cognate epitope rank") +
  xlab("Number of VDJdb entries for the epitope") +
  scale_y_log10()
```

